Universe              = vanilla
executable            = <executable>
arguments             = $(ProcId)
GetEnv                = True
+Remote_Schedd = "bird-htc-sched11.desy.de"
output                = output/$(ClusterId).$(ProcId).out
error                 = error/$(ClusterId).$(ProcId).err
log                   = log/$(ClusterId).log
requirements 	        = (OpSysAndVer =?= "CentOS7")
# request_memory        = 4 GB
+RequestRuntime       = <run_time>

queue <n_jobs>
